### ISSUE TITLE
Pastanaga UI styling for folder contents

### ISSUE THREAD

**Issue by tisto** [plone/volto#1328]
# Desktop

![51E85D98-7DF6-4491-A469-C8F976A9C069](https://user-images.githubusercontent.com/632105/78367081-d0c60e00-75c1-11ea-831d-308a17eca85a.png)

![2393F88A-F3A4-457D-B937-F12EB345C7B2](https://user-images.githubusercontent.com/632105/78367163-ed624600-75c1-11ea-91b1-aa1568a41e2c.png)

# Edit Menu

![48F2FF32-3E6B-4A94-94CE-DD0F22351FE7](https://user-images.githubusercontent.com/632105/78367258-0f5bc880-75c2-11ea-9f1c-3f681e272703.png)

# Plone Classic Tooltips

<img width="607" alt="Screenshot 2020-04-03 at 18 04 48" src="https://user-images.githubusercontent.com/632105/78381467-b138e080-75d5-11ea-9d97-957563164675.png">

# ToDo

- [X] Update icons to use the most recent Pastanaga UI icons
- [X] Main table styling (colors, table, frame, icons)
- [X] Style the menus
- [ ] Style pagination
- [X] Style toolbar
- [X] Style search
- [ ] Cypress tests for all folder_content functionality
- [X] Add real tooltip to folder contents toolbar (rename, tags, cut, paste, copy, delete, etc.)
