### ISSUE TITLE
Undo Control Panel

### ISSUE THREAD

**Issue by tisto** [plone/volto#2049]
**Is your feature request related to a problem? Please describe.**

The undo control panel is hidden in the ZMI (mainly because in most cases the undo functionality does not work). Though, even if undo does not work it gives a very good overview of what happens.

**Describe the solution you'd like**

Add a new "undo control panel" that lists all the entries of the ZMI listing. Make it filterable by user/date/path.

**Describe alternatives you've considered**

Giving users access to the ZMI is not a viable option.

**Screenshot Undo in ZMI**

![Zope-on-https-plonedemo-kitconcept-com](https://user-images.githubusercontent.com/632105/161379910-ce177044-159a-4b97-9c8c-633f15db5bcd.png)

**ToDo**

* [x] create a plone.restapi endpoint for undo operations
* [x] create a Volto control panel that lists all the possible undo operations (newest first)
* [x] allow administrators to undo a single transaction
* [x] allow administrators to undo multiple transactions
* [x] allow administrators to filter transactions by path
* [x] allow administrators to filter transactions by date/time
* [x] allow administrators to filter transactions by user

**Comment by sneridagh** [comment]
Closing as implemented in Volto 16.

**Comment by tisto** [comment]
Implemented in https://github.com/plone/volto/pull/3457.

**Comment by davisagli** [comment]
Oh wow, I never noticed it was there!
