### ISSUE TITLE
Volto 18 Release Todo Checklist

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#6123]
- [x] Update the docs with new makefile targets https://github.com/plone/documentation/blob/6.0/docs/install/create-project.md?plain=1#L396
- [x] Release new images based in pnpm as default 
- [x] https://github.com/plone/documentation/issues/1705
- [x] https://github.com/plone/documentation/issues/1706
- [x] https://github.com/plone/documentation/issues/1707
- [x] https://github.com/plone/documentation/pull/1714

**Comment by stevepiercy** [comment]
Closing as completed.
